spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lec-9-db
    username: postgres
    password: 2100401
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

api:
  prefix: /api/v1
